# Análise exploratória dos dados
A seguir, vamos fazer a parte da EDA do projeto. Específicamente da tabela `alunos_alfabetizacao` da camada Gold que foi construída no tech challenge da fase 2.

## Pergunta norteadora
Dado o contexto do aluno, da escola e do município, é possível prever se um aluno será considerado alfabetizado?

## Variável Target
Nossa variável target será a coluna `alfabetizado`, respondendo a pergunta norteadora se um aluno será considerado alfabetizado ou não.

In [1]:
# Instalação do matplotlib e seaborn para importar as bibliotecas
!pip install matplotlib seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in C:\Users\carol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.11.1)
Requirement already satisfied: seaborn in C:\Users\carol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\carol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\carol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\carol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\carol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.25 in C:\Users\carol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (2.4.4)
Requirement already satisfied: packaging>=20.0 in C:\Users\carol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in C:\Users\carol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\carol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\carol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in C:\Users\carol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: pytz>=2020.1 in C:\Users\carol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\carol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\carol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: C:\Users\carol\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
# Importações
# Utilizaremos pandas para ler o arquivo de dados
import pandas as pd

# Matplotlib e Seaborn para podermos plotar os gráficos
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Carregando os dados, que são provenientes da fase 2
df_alfabetizacao = pd.read_parquet("../data/gold/alunos_alfabetizacao.parquet")

In [4]:
df_alfabetizacao.head()

,ano,id_aluno,id_escola,id_municipio,id_municipio_nome,sigla_uf,sigla_uf_nome,serie,rede,presenca,...,icg_nivel_5,icg_nivel_6,tdi_ef_2_ano_anterior,taxa_aprovacao_ef_2_ano_anterior,taxa_reprovacao_ef_2_ano_anterior,taxa_abandono_ef_2_ano_anterior,inse_medio,quantidade_escolas_inse,alfabetizado,_gold_processed_at
0,2023,11017171,60000268,1101492,São Francisco do Guaporé,RO,Rondônia,2° ano do Ensino Fundamental,Municipal,Ausente,...,5.9,NaN,1.2,100.0,0.0,0.0,4.955714,7.0,Não,2026-08-26 21:03:06.773202
1,2023,13026795,60001172,1302603,Manaus,AM,Amazonas,2° ano do Ensino Fundamental,Municipal,Ausente,...,NaN,0.0,4.7,98.1,1.4,0.5,4.853928,527.0,Não,2026-08-26 21:03:06.773202
2,2023,15057176,60001748,1504422,Marituba,PA,Pará,2° ano do Ensino Fundamental,Municipal,Ausente,...,0.0,NaN,5.0,98.7,0.2,1.1,4.501522,46.0,Não,2026-08-26 21:03:06.773202
3,2023,15090103,60002799,1506807,Santarém,PA,Pará,2° ano do Ensino Fundamental,Municipal,Ausente,...,0.0,2.1,3.4,94.0,5.8,0.2,4.262667,195.0,Não,2026-08-26 21:03:06.773202
4,2023,15037662,60002957,1502400,Castanhal,PA,Pará,2° ano do Ensino Fundamental,Municipal,Ausente,...,NaN,NaN,10.3,91.8,7.6,0.6,4.454194,62.0,Não,2026-08-26 21:03:06.773202

In [5]:
df_alfabetizacao.describe().round(2)

,ano,id_aluno,id_escola,id_municipio,peso_aluno,taxa_alfabetizacao_municipio,media_portugues_municipio,taxa_alfabetizacao_uf,media_portugues_uf,proficiencia,...,icg_nivel_4,icg_nivel_5,icg_nivel_6,tdi_ef_2_ano_anterior,taxa_aprovacao_ef_2_ano_anterior,taxa_reprovacao_ef_2_ano_anterior,taxa_abandono_ef_2_ano_anterior,inse_medio,quantidade_escolas_inse,_gold_processed_at
count,1747439.0,1747439.0,1747439.0,1747439.0,1502809.00,1746385.00,1746385.00,1747439.00,1747439.00,1502809.00,...,1746760.00,605870.00,624743.00,1747399.00,1747399.00,1747399.00,1747399.00,1746238.00,1746238.00,1747439
mean,2023.0,31649371.14,60021081.99,3169498.22,1.16,57.43,746.31,57.45,746.32,747.56,...,2.01,0.95,6.12,4.74,97.41,2.21,0.38,4.83,112.89,2026-08-26 21:03:06.773202
min,2023.0,11000001.0,60000001.0,1100015.0,0.10,2.12,673.30,30.57,712.56,578.46,...,0.00,0.00,0.00,0.00,68.40,0.00,0.00,3.50,1.00,2026-08-26 21:03:06.773202
25%,2023.0,24002869.5,60009751.0,2402006.0,1.00,46.72,734.09,49.20,736.07,718.84,...,0.70,0.00,0.00,1.90,97.10,0.00,0.00,4.50,12.00,2026-08-26 21:03:06.773202
50%,2023.0,31089634.0,60020359.0,3131307.0,1.09,57.00,743.96,58.74,747.42,752.15,...,1.60,0.00,0.50,3.80,98.90,0.50,0.20,4.86,32.00,2026-08-26 21:03:06.773202
75%,2023.0,41105907.5,60034237.0,4119509.0,1.24,67.75,755.55,63.65,752.13,778.73,...,2.70,0.30,2.10,6.20,99.80,2.30,0.50,5.19,93.00,2026-08-26 21:03:06.773202
max,2023.0,52083816.0,60042811.0,5222302.0,142.55,100.00,868.46,84.49,795.73,904.38,...,50.00,100.00,100.00,42.60,100.00,31.60,7.10,5.98,1213.00,2026-08-26 21:03:06.773202
std,0.0,10834071.9,13132.93,1082193.25,0.48,16.39,20.87,12.03,15.84,48.23,...,1.86,4.57,17.53,3.93,3.93,3.86,0.63,0.44,227.89,NaN

In [6]:
df_alfabetizacao.dtypes

ano                                           Int64
id_aluno                                      Int64
id_escola                                     Int64
id_municipio                                  Int64
id_municipio_nome                    string[python]
sigla_uf                                     object
sigla_uf_nome                        string[python]
serie                                string[python]
rede                                 string[python]
presenca                             string[python]
preenchimento_caderno                string[python]
peso_aluno                                  float64
taxa_alfabetizacao_municipio                float64
media_portugues_municipio                   float64
taxa_alfabetizacao_uf                       float64
media_portugues_uf                          float64
proficiencia                                float64
populacao                                     Int64
pib                                         float64
pib_per_capita                              Float64
atu_ef_anos_iniciais                        float64
had_ef_anos_iniciais                        float64
dsu_ef_anos_iniciais                        float64
afd_ef_anos_iniciais_grupo_1                float64
ird_alta                                    float64
ird_baixa_regularidade                      float64
icg_nivel_1                                 float64
icg_nivel_2                                 float64
icg_nivel_3                                 float64
icg_nivel_4                                 float64
icg_nivel_5                                 float64
icg_nivel_6                                 float64
tdi_ef_2_ano_anterior                       float64
taxa_aprovacao_ef_2_ano_anterior            float64
taxa_reprovacao_ef_2_ano_anterior           float64
taxa_abandono_ef_2_ano_anterior             float64
inse_medio                                  float64
quantidade_escolas_inse                     float64
alfabetizado                         string[python]
_gold_processed_at                   datetime64[us]
dtype: object

In [7]:
df_alfabetizacao.isnull().sum()

ano                                        0
id_aluno                                   0
id_escola                                  0
id_municipio                               0
id_municipio_nome                          0
sigla_uf                                   0
sigla_uf_nome                              0
serie                                      0
rede                                       0
presenca                                   0
preenchimento_caderno                      0
peso_aluno                            244630
taxa_alfabetizacao_municipio            1054
media_portugues_municipio               1054
taxa_alfabetizacao_uf                      0
media_portugues_uf                         0
proficiencia                          244630
populacao                                  0
pib                                        0
pib_per_capita                             0
atu_ef_anos_iniciais                       0
had_ef_anos_iniciais                   71504
dsu_ef_anos_iniciais                     577
afd_ef_anos_iniciais_grupo_1             485
ird_alta                                  52
ird_baixa_regularidade                    38
icg_nivel_1                              485
icg_nivel_2                              485
icg_nivel_3                              577
icg_nivel_4                              679
icg_nivel_5                          1141569
icg_nivel_6                          1122696
tdi_ef_2_ano_anterior                     40
taxa_aprovacao_ef_2_ano_anterior          40
taxa_reprovacao_ef_2_ano_anterior         40
taxa_abandono_ef_2_ano_anterior           40
inse_medio                              1201
quantidade_escolas_inse                 1201
alfabetizado                               0
_gold_processed_at                         0
dtype: int64

In [8]:
# Exibindo total de alunos alfabetizados, separados por sim/não
print(f"Quantidade da coluna {df_alfabetizacao["alfabetizado"].value_counts()}")
print(f"Proporção da coluna {(df_alfabetizacao["alfabetizado"].value_counts(normalize=True) * 100).round(2)}")

Quantidade da coluna alfabetizado
Sim    877427
Não    870012
Name: count, dtype: Int64
Proporção da coluna alfabetizado
Sim    50.21
Não    49.79
Name: proportion, dtype: Float64

In [11]:
for colunas_categoricas in ["id_municipio_nome","sigla_uf","sigla_uf_nome", "alfabetizado", "serie", "rede", "presenca", "preenchimento_caderno"]:
    print(f"Coluna: {df_alfabetizacao[colunas_categoricas].value_counts()}")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

Coluna: id_municipio_nome
Rio de Janeiro           54533
Manaus                   33096
Belo Horizonte           21086
Fortaleza                20171
Salvador                 16101
                         ...
Tupirama                    11
Santo Expedito do Sul       10
Rio dos Índios              10
Paiva                       10
Conceição de Ipanema        10
Name: count, Length: 4652, dtype: Int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Coluna: sigla_uf
MG    210107
RJ    159997
PR    138532
BA    137724
RS    121148
PA    104972
SC    102621
CE    100349
PE     88271
GO     83741
MA     74958
AM     63055
MT     54526
ES     50482
MS     42199
PB     38215
AL     35503
PI     35415
RN     31748
RO     22834
TO     20059
SE     18634
AP     12349
Name: count, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Coluna: sigla_uf_nome
Minas Gerais           210107
Rio de Janeiro         159997
Paraná                 138532
Bahia                  137724
Rio Grande do Sul      121148
Pará                   104972
Santa Catarina         102621
Ceará                  100349
Pernambuco              88271
Goiás                   83741
Maranhão                74958
Amazonas                63055
Mato Grosso             54526
Espírito Santo          50482
Mato Grosso do Sul      42199
Paraíba                 38215
Alagoas                 35503
Piauí                   35415
Rio Grande do Norte     31748
Rondônia                22834
Tocantins               20059
Sergipe                 18634
Amapá                   12349
Name: count, dtype: Int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Coluna: alfabetizado
Sim    877427
Não    870012
Name: count, dtype: Int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Coluna: serie
2° ano do Ensino Fundamental    1747439
Name: count, dtype: Int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Coluna: rede
Municipal    1592299
Estadual      155140
Name: count, dtype: Int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Coluna: presenca
Presente    1503058
Ausente      244381
Name: count, dtype: Int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Coluna: preenchimento_caderno
Prova preenchida        1502809
Prova não preenchida     244630
Name: count, dtype: Int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [12]:
todas_ufs = {"AC","AL","AP","AM","BA","CE","DF","ES","GO","MA","MT","MS","MG","PA","PB","PR","PE","PI","RJ","RN","RS","RO","RR","SC","SP","SE","TO"}
ufs_presentes = set(df_alfabetizacao["sigla_uf"].dropna().unique())

print("UFs faltando:", todas_ufs - ufs_presentes)

UFs faltando: {'DF', 'AC', 'SP', 'RR'}

**Limitação**: faltam 4 UFs inteiras na base: SP, AC, RR e DF. </br>
SP é a mais grave, por ser o estado mais populoso do Brasil, qualquer modelo treinado aqui não pode ser generalizado para esse estado.

In [ ]:
# Identificando outlier presente na coluna "peso_aluno", confirmando que é acima de 0.999
print(df_alfabetizacao["peso_aluno"].quantile([0.95, 0.99, 0.999, 1.0]))

0.950      1.603785
0.990      2.158272
0.999      4.579347
1.000    142.545400
Name: peso_aluno, dtype: float64

In [15]:
# Descobrindo de quais UFs estão vindo os outliers
df_alfabetizacao.nlargest(10, "peso_aluno")[["id_aluno","sigla_uf","id_municipio_nome","rede","peso_aluno"]]

         id_aluno sigla_uf       id_municipio_nome       rede  peso_aluno
1320835  33043600       RJ                   Macaé  Municipal  142.545400
195074   33113247       RJ          Rio de Janeiro  Municipal  116.004200
1072457  42061530       SC               Joinville  Municipal  113.061711
655487   33060043       RJ             Nova Iguaçu  Municipal  108.144928
1693199  33028603       RJ         Duque de Caxias  Municipal  105.356600
973316   33047350       RJ                    Magé  Municipal   95.448040
670152   33055617       RJ                 Niterói  Municipal   79.724580
371321   29089205       BA  Santo Antônio de Jesus  Municipal   72.564544
1656260  26064181       PE           Serra Talhada  Municipal   71.484241
1460217  33134793       RJ             São Fidélis  Municipal   67.698190